#!/data/data/com.termux/files/usr/bin/env bash

VERSION="0.3.4"
NAME="mandy"
URL="https://github.com/angeldollface/$NAME/archive/refs/tags/v.$VERSION.tar.gz"

build(){
    wget $URL
    tar -xvzf "v.$VERSION.tar.gz"
    mv "$NAME-v.$VERSION" "$NAME-bin"
    cd "$NAME-bin"
    cargo build --release --bin mandy
    chmod a+x "target/release/$NAME"
    mv "target/release/$NAME" $PREFIX/bin
    cd ..
    rm -rf "$NAME-bin" *.tar.gz
}

build
