name: TErmux Doll CI
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: "Set up Python ${{ matrix.python-version }}."
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install dependencies."
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: "Run the Repo build script."
        run: cd src && bash build_repo.sh
      - name: "Deploy."
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: output